# Tensor Manipulation

** Author : Sangkeun Jung (hugmanskj@gmail.com)**

More than 70% of tensorflow codes are about 'tensor' manipulation code.
We should be familar to tensor object, operations. 

Most of the tensor api is similar to numpy api. So, it's a good idea to study numpy api first. 

## *Numpy n-dimensional array*  and     *tf.Tensor*

In [2]:
import tensorflow as tf
import numpy as np

C:\Users\juni\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
n_a = np.arange(100)
n_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
print(type(n_a))
n_a.shape

<class 'numpy.ndarray'>


(100,)

In [11]:
t_a = tf.Variable(n_a)
print("t_a : ", t_a)
sess = tf.Session()

# init all variables
sess.run(tf.global_variables_initializer())

t_a :  <tf.Variable 'Variable_3:0' shape=(100,) dtype=int32_ref>


* numpy obj can be compatible to tf.tensor
* the result of sess.run() is always numpy obj or a list of numpy objs 

In [13]:
print("value of t_a : ")
print(sess.run(t_a))
print()
print("type of sess.run(t_a) : ", type(sess.run(t_a)))
print("shape of sess.run(t_a) : ", sess.run(t_a).shape)


value of t_a : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

type of sess.run(t_a) :  <class 'numpy.ndarray'>
shape of sess.run(t_a) :  (100,)


## Reshape

In [27]:
n_b = np.arange(20).reshape(4,5)
print(n_b.shape)
n_b

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
n_c = n_b.reshape(2,10)
print(n_c.shape)
print(n_c)

(2, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


- tf.reshape(tensor, [dim, dim, ...] ) : reshape a tensor with dimension information

In [17]:
# [4,5] --> [5,4]
t_r = tf.reshape(n_b, [5,4])
print(t_r)
print(sess.run(t_r))

Tensor("Reshape:0", shape=(5, 4), dtype=int32)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [18]:
# [4,5] --> [1,20]
t_r2 = tf.reshape(n_b, [1,20])
print(t_r2)
print(sess.run(t_r2))

Tensor("Reshape_1:0", shape=(1, 20), dtype=int32)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


- We can use **-1** for dimension inference (very useful!!!) 

In [21]:
t_r3 = tf.reshape(n_b, [10, -1])  # second dim. will be inferenced! row-10에 맞춰서 col을 예상한다.
print(t_r3)  
print(sess.run(t_r3))

Tensor("Reshape_3:0", shape=(10, 2), dtype=int32)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [22]:
t_r4 = tf.reshape(n_b, [-1])
print(t_r4)
print(sess.run(t_r4))

Tensor("Reshape_4:0", shape=(20,), dtype=int32)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Split & Concat

- tf.split(split_dim, num_split, value, name='split')
> Splits a tensor into num_split tensors along one dimension.

- tf.concat(concat_dim, values, name='concat')
> Concatenates tensors along one dimension.

In [39]:
t_h = tf.split(n_b,5,1)
result = sess.run(t_h)
print("type of result t_h : ", type(result))
print("len. of result t_h : ", len(result))
print("Shape of splitted element : ", result[0].shape)
for i in result: print(i); print("-------")
    
print("#"*20)

t_h_c = tf.concat(result,1)
print(t_h_c)
print(sess.run(t_h_c))

type of result t_h :  <class 'list'>
len. of result t_h :  5
Shape of splitted element :  (4, 1)
[[ 0]
 [ 5]
 [10]
 [15]]
-------
[[ 1]
 [ 6]
 [11]
 [16]]
-------
[[ 2]
 [ 7]
 [12]
 [17]]
-------
[[ 3]
 [ 8]
 [13]
 [18]]
-------
[[ 4]
 [ 9]
 [14]
 [19]]
-------
####################
Tensor("concat_2:0", shape=(4, 5), dtype=int32)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [44]:
# vertical split
t_v = tf.split(n_b,4,0)
result = sess.run(t_v)
print("type of result t_v : ", type(result))
print( "len. of result t_v : ", len(result))
print("Shape of splitted element : ", result[0].shape)
for i in result: print(i); print("-"*20)
    
print("#"*20)

t_v_c = tf.concat(result,0)
print(t_v_c)
print(sess.run(t_v_c))

type of result t_v :  <class 'list'>
len. of result t_v :  4
Shape of splitted element :  (1, 5)
[[0 1 2 3 4]]
--------------------
[[5 6 7 8 9]]
--------------------
[[10 11 12 13 14]]
--------------------
[[15 16 17 18 19]]
--------------------
####################
Tensor("concat_7:0", shape=(4, 5), dtype=int32)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Expand  & Squeeze

- tf.expand_dims(input, dim, name=None)
> Inserts a dimension of 1 into a tensor's shape.

- tf.squeeze(input, squeeze_dims=None, name=None)
> Removes dimensions of size 1 from the shape of a tensor.

In [49]:
n_d = np.arange(9).reshape(3,3)
print("Shape : ", n_d.shape)
print(n_d)

Shape :  (3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [50]:
# insert new dim. at 0
t_d_0 = tf.expand_dims(n_d, 0)
print(t_d_0)
print(sess.run(t_d_0))

print("#"*20)

t_s_0 = tf.squeeze(t_d_0)
print(t_s_0)
print(sess.run(t_s_0))


Tensor("ExpandDims_2:0", shape=(1, 3, 3), dtype=int32)
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
####################
Tensor("Squeeze_2:0", shape=(3, 3), dtype=int32)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [54]:
# insert new dim. at 1
t_d_1 = tf.expand_dims(n_d, 1)
print(t_d_1)
print(sess.run(t_d_1))

print("="*20)

t_s_1 = tf.squeeze(t_d_1)
print(t_s_1)
print(sess.run(t_s_1))


Tensor("ExpandDims_4:0", shape=(3, 1, 3), dtype=int32)
[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
Tensor("Squeeze_6:0", shape=(3, 3), dtype=int32)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
# expand two times
t_d_2 = tf.expand_dims(n_d, 2)
print t_d_2
print sess.run(t_d_2)
t_d_3 = tf.expand_dims(t_d_2, 3)
print t_d_3
print sess.run(t_d_3)

print "="*20

# --> squeeze all dimensions which have 1 dim.
t_s_3 = tf.squeeze(t_d_3)
print t_s_3
print sess.run(t_s_3)

Tensor("ExpandDims_2:0", shape=(3, 3, 1), dtype=int64)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]
Tensor("ExpandDims_3:0", shape=(3, 3, 1, 1), dtype=int64)
[[[[0]]

  [[1]]

  [[2]]]


 [[[3]]

  [[4]]

  [[5]]]


 [[[6]]

  [[7]]

  [[8]]]]
Tensor("Squeeze_2:0", shape=(3, 3), dtype=int64)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Pack & Unpack

- tf.pack(values, axis=0, name='pack')
> Packs **a list of rank-R tensors** into one rank-(R+1) tensor.

- tf.unpack(value, num=None, axis=0, name='unpack')
> Unpacks the given dimension of a rank-R tensor into rank-(R-1) **tensors**.

In [19]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

list_n = [x,y,z]



In [20]:
# pack at axis=0
t_p = tf.pack(list_n)
print t_p
print sess.run(t_p)

print "="*20

t_u = tf.unpack(t_p)
print t_u
print
for i in t_u: print i
print
for i in t_u: print sess.run(i)

Tensor("pack:0", shape=(3, 3), dtype=int32)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[<tf.Tensor 'unpack:0' shape=(3,) dtype=int32>, <tf.Tensor 'unpack:1' shape=(3,) dtype=int32>, <tf.Tensor 'unpack:2' shape=(3,) dtype=int32>]

Tensor("unpack:0", shape=(3,), dtype=int32)
Tensor("unpack:1", shape=(3,), dtype=int32)
Tensor("unpack:2", shape=(3,), dtype=int32)

[1 2 3]
[4 5 6]
[7 8 9]


- Aware that we can do samething with tf.split & tf.reshape.
- But we should know the split_numbers (in this case 3 ), and target shape

In [21]:
t_sp = tf.split(0, 3, t_p)
print t_sp
for i in t_sp: print i
print
for i in t_sp: print sess.run(i)

[<tf.Tensor 'split_2:0' shape=(1, 3) dtype=int32>, <tf.Tensor 'split_2:1' shape=(1, 3) dtype=int32>, <tf.Tensor 'split_2:2' shape=(1, 3) dtype=int32>]
Tensor("split_2:0", shape=(1, 3), dtype=int32)
Tensor("split_2:1", shape=(1, 3), dtype=int32)
Tensor("split_2:2", shape=(1, 3), dtype=int32)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


## Transpose

- tf.transpose(a, perm=None, name='transpose')
> Transposes a. Permutes the dimensions according to perm.

In [22]:
n_t = np.arange(8).reshape(2,4)
print n_t.shape
print n_t

(2, 4)
[[0 1 2 3]
 [4 5 6 7]]


In [23]:
t_tr = tf.transpose(n_t)
print t_tr
print sess.run(t_tr)

print "="*20
# reverse transpose 
t_tr_r = tf.transpose(t_tr)
print t_tr_r
print sess.run(t_tr_r)

Tensor("transpose:0", shape=(4, 2), dtype=int64)
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
Tensor("transpose_1:0", shape=(2, 4), dtype=int64)
[[0 1 2 3]
 [4 5 6 7]]


## Create tensor with initial values

- tf.ones(shape, dtype=tf.float32, name=None)
> Creates a tensor with all elements set to 1.
- tf.zeros(shape, dtype=tf.float32, name=None)
> Creates a tensor with all elements set to zero.
- tf.fill(dims, value, name=None)
> Creates a tensor filled with a scalar value.

In [24]:
t_1 = tf.ones([2,7])
print t_1
print sess.run(t_1)

Tensor("ones:0", shape=(2, 7), dtype=float32)
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [25]:
t_0 = tf.zeros([2,7])
print t_0
print sess.run(t_0)

Tensor("zeros:0", shape=(2, 7), dtype=float32)
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [26]:
t_f = tf.fill([2,7], 77)
print t_f
print sess.run(t_f)

Tensor("Fill:0", shape=(2, 7), dtype=int32)
[[77 77 77 77 77 77 77]
 [77 77 77 77 77 77 77]]


## Copy shape of other tensor

- tf.ones_like(tensor, dtype=None, name=None, optimize=True)
> Creates a tensor with all elements set to 1.
- tf.zeros_like(tensor, dtype=None, name=None, optimize=True)
> Creates a tensor with all elements set to zero.

In [27]:
n_sh = np.arange(20).reshape(4,5)
print n_sh.shape
print n_sh

(4, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [28]:
t_o = tf.ones_like(n_sh)
print t_o
print sess.run(t_o)

Tensor("ones_like:0", shape=(4, 5), dtype=int64)
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [29]:
t_z = tf.zeros_like(n_sh)
print t_z
print sess.run(t_z)

Tensor("zeros_like:0", shape=(4, 5), dtype=int64)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Tiling tensor 

- tf.tile(input, multiples, name=None)
> Constructs a tensor by tiling a given tensor.

In [30]:
n_r = np.arange(3)
print n_r.shape
print n_r

(3,)
[0 1 2]


In [31]:
# tile to horizontal
t_ti = tf.tile(n_r, [3])
print t_ti
print sess.run(t_ti)

Tensor("Tile:0", shape=(9,), dtype=int64)
[0 1 2 0 1 2 0 1 2]


In [32]:
n_r2 = np.arange(6).reshape(2,3)
print n_r2.shape
print n_r2

(2, 3)
[[0 1 2]
 [3 4 5]]


In [33]:
# tile to horizontal & vertical
t_ti2 = tf.tile(n_r2, [2,3])
print t_ti2
print sess.run(t_ti2)

Tensor("Tile_1:0", shape=(4, 9), dtype=int64)
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
